### ISSUE TITLE
FE: Create UserInfo component and insert it into Header.

### ISSUE THREAD

**Issue by cjrpostma** [learn-able/learnable-fe#59]
- Follow wireframes for guidance on composition.
- See if you can render the UserInfo component into the Header (you'll need to wrap the UserInfo component within Header).
- See if you can use Styled Components to style the Header and UserInfo components to appear close to the rest of the app/wireframes.
- See if you can use the icons from Material UI via the pattern in other components within the app (check out PlaylistView3, you'll see the icons imported at the top).
- Try to focus on the layout and positioning. See if you can use flexbox within Styled Components to position elements.

**Comment by ryanbahan** [comment]
- create a new component called UserInfo
    - create a new folder for the UserInfo component in the directory
    - create a new javascript file in that UserInfo folder
    - move your UserInfo styling from Header.js into UserInfo
    - use that UserInfo component in the Header component
    - get content from UserInfo component to display on the browser
