### ISSUE TITLE
Fix playlist item bug

### ISSUE THREAD

**Issue by ryanbahan** [learn-able/learnable-fe#86]
When checking and unchecking a box on the app, the icon and title for the playlistItem now dissapear.

**Comment by ryanbahan** [comment]
<img width="370" alt="Screen Shot 2020-06-01 at 1 30 16 PM" src="https://user-images.githubusercontent.com/54119863/83446529-0cd3ee80-a40c-11ea-9ea0-b645ecbec4e2.png">

**Comment by ryanbahan** [comment]
playlist item data: 
<img width="396" alt="Screen Shot 2020-06-01 at 1 31 41 PM" src="https://user-images.githubusercontent.com/54119863/83446644-41e04100-a40c-11ea-96a6-01f848c64136.png">

**Comment by alerrian** [comment]
Yep, this is what I was referring to when I talked about sending the whole thing through the patch. So you'll want to modify the patch that is going out for the `is_complete` PATCH request so that it sends out all of the data for the `playlistItem` that is being updated.

**Comment by cjrpostma** [comment]
Ryan, want me to update this in my branch since I'm already working in that file?

**Comment by ryanbahan** [comment]
@cjrpostma yeah if you can pull the latest updates from master and fix this on your branch that would be awesome.

**Comment by cjrpostma** [comment]
Consider it done!
