### ISSUE TITLE
FE: Fix horizontal scrolling of playlists.

### ISSUE THREAD

**Issue by cjrpostma** [learn-able/learnable-fe#88]

**Comment by ryanbahan** [comment]
@cjrpostma what's wrong with the horizontal scroll?

**Comment by cjrpostma** [comment]
> @cjrpostma what's wrong with the horizontal scroll?

Just checked again and it looks as though it was fixed in a recent PR and is working perfectly now. The ticket just needs to be closed. I'll close it now.
